#!/bin/sh

BASEDIR=$(dirname "$0")

VERINICEDBSERVER=${VERINICEDBSERVER:-127.0.0.1:5432}
VERINICEDB=${VERINICEDB:-verinicedb_test}
VERINICEUSER=${VERINICEUSER:-verinice}
VERINICEPASSWORD=${VERINICEPASSWORD:-verinice}
VERINICEDUMP=${VERINICEDUMP:-$BASEDIR/verinice-rest/src/test/resources/test-dump.sql}
SPRINGDELAY=${SPRINGDELAY:-15}

# refresh the verinice database
if ! (psql -qd postgres -c "DROP DATABASE IF EXISTS $VERINICEDB" \
	&& createdb -O $VERINICEUSER $VERINICEDB \
	&& psql -q -U $VERINICEUSER -d $VERINICEDB -f $VERINICEDUMP > /dev/null)
then
	echo "Unable to clean up database $VERINICEDB."
	exit 1
fi

export spring_datasource_url="jdbc:postgresql://$VERINICEDBSERVER/$VERINICEDB"
export spring_datasource_username="$VERINICEUSER"
export spring_datasource_password="$VERINICEPASSWORD"

mvn -B -pl verinice-rest spring-boot:run &
spring_pid=$!

sleep $SPRINGDELAY

CURDIR=$PWD
cd $BASEDIR/verinice-rest/src/test/python
python3 api_test.py
cd $CURDIR

## clean up
kill $spring_pid
